### ISSUE TITLE
Missing feature: Performance metrics

### ISSUE THREAD

**Issue by battleblow** [battleblow/openjdk-jdk11u#16]
See

```
src/hotspot/os/bsd/os_perf_bsd.cpp
```

Many of the methods in this file only have MacOS X implementations.

**Comment by bsdkurt** [comment]
I created a feature branch and merged a few pull requests from me and @devnexen into it: `bsd-port-os-perf-bsd`. @battleblow when you get a chance please take a look at it. If you could do test builds on FreeBSD/NetBSD that would be greatly appreciated.

**Comment by battleblow** [comment]
We've merged all of these changes in and should now be functionally complete in terms of emitting performance information.  There are a few edge cases (e.g. FreeBSD and cpuset), but overall we're done with development for this.
