### ISSUE TITLE
setupDebuggerBsd: BSD only supported on x86/x86_64

### ISSUE THREAD

**Issue by MikaelUrankar** [battleblow/openjdk-jdk11u#55]
I'm seeing this error on aarch64 when running some tests. It comes from here: https://github.com/battleblow/openjdk-jdk11u/blob/master/src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/HotSpotAgent.java#L631

Is it related to the code (for ppc64) we've added in https://github.com/battleblow/openjdk-jdk11u/commit/411c1db44f955e16d240aed826ffbae467e0b909#diff-7b655388e6f66eee425f4aeda3bd5c3a?

**Comment by battleblow** [comment]
Curtis just made a change to add powerpc64 support.  You would need a similar change to add aarch64 support.

**Comment by battleblow** [comment]
Mikael, can you take a look at the pull request from Curtis for aarch64 support and preferably test it out?

**Comment by MikaelUrankar** [comment]
It's already in my pull request:
https://github.com/battleblow/openjdk-jdk11u/pull/50/commits/0aaf2d8c5da9f9b1f4a18272fcd1779f5f724aa8

**Comment by battleblow** [comment]
I think we can close this now that Curtis has added powerpc64 support and you've added aarch64 support.
