### ISSUE TITLE
Setting/getting socket options fails on FreeBSD

### ISSUE THREAD

**Issue by battleblow** [battleblow/openjdk-jdk11u#63]
Some internal JDK tests are failing on FreeBSD during calls to set socket options.  In particular, the following two produce failures:

* jdk/java/net/SocketOption/OptionsTest.java
* jdk/jdk/net/Sockets/SupportedOptions.java

The call to setsockopt is throwing EINVAL in each case.  The same tests pass on OpenBSD, so this appears to be restricted to FreeBSD.  Tested on both FreeBSD 11 and 12.

**Comment by battleblow** [comment]
Note that the error cases noted so far are particularly calls to setsockopt which are attempting to set IP_TOS.  Based on some debugging, the parameters to the call look correct:

E.g. Socket: 8, Level: 0, Opt: 3, Optval: 16, Len: 4

0 = IPPROTO_IP
3 = IP_TOS
16 = IPTOS_LOWDELAY
4 = sizeof(int)

**Comment by battleblow** [comment]
This is also impacting

* jdk/java/net/Socket/TrafficClass.java

Possibly related, the following tests report EINVAL attempting to get a socket option:

* jdk/java/net/DatagramSocket/ReuseAddressTest.java

**Comment by battleblow** [comment]
Note that the last test fails (ReuseAddressTest) in my OpenBSD VM, so it may be a separate issue.  All the setsockopt tests pass though.

**Comment by battleblow** [comment]
Simple test case for setting IP_TOS:

```
import java.net.*;
import jdk.net.*;

public
class TestTos {
    public static
    void main(String[] args)
        throws Exception {

        ServerSocket ss = new ServerSocket();
        Sockets.setOption(ss, StandardSocketOptions.IP_TOS, 0x10);
    }
}
```

**Comment by battleblow** [comment]
Some code references:

* https://github.com/battleblow/openjdk-jdk11u/blob/master/src/java.base/unix/native/libnet/PlainSocketImpl.c#L904
* https://github.com/battleblow/openjdk-jdk11u/blob/master/src/java.base/unix/native/libnet/net_util_md.c#L1442

**Comment by battleblow** [comment]
The following test failures may also be related to this:

* jdk/java/net/MulticastSocket/B6427403.java
* jdk/java/net/MulticastSocket/JoinLeave.java
* jdk/java/net/MulticastSocket/Promiscuous.java
* jdk/java/net/MulticastSocket/SetLoopbackMode.java
* jdk/java/net/MulticastSocket/SetOutgoingIf.java
* jdk/java/net/MulticastSocket/Test.java

All have at least one failing test which traces to a SocketException with the error "Invalid argument" (a translation of EINVAL) in PlainDatagramSocketImpl.join(), which makes a number of setsockopt calls.  The failure being tied to one of those calls still needs to be confirmed though.

Source code references:

* https://github.com/battleblow/openjdk-jdk11u/blob/master/src/java.base/unix/native/libnet/PlainDatagramSocketImpl.c#L2206
* https://github.com/battleblow/openjdk-jdk11u/blob/master/src/java.base/unix/native/libnet/PlainDatagramSocketImpl.c#L1896

**Comment by battleblow** [comment]
Some relevant selected truss output for the test case I included above:

```
35842 100668: socket(PF_INET6,SOCK_STREAM,0)     = 6 (0x6)
35842 100668: setsockopt(6,IPPROTO_IPV6,IPV6_V6ONLY,0x7fffdfffd7c0,4) = 0 (0x0)
35842 100668: getsockopt(6,SOL_SOCKET,SO_TYPE,0x7fffdfffd770,0x7fffdfffd774) = 0 (0x0)
35842 100668: setsockopt(6,SOL_SOCKET,SO_REUSEADDR,0x7fffdfffd7c4,4) = 0 (0x0)
35842 100668: setsockopt(6,IPPROTO_IP,IP_TOS,0x7fffdfffd710,4) ERR#22 'Invalid argument
```

To be clear, this is defaulting to creating an IPv6 socket, but then passing IPPROTO_IP (rather than IPPROTO_IPV6) to the final invocation of setsockopt.  I assume this is what results in the EINVAL.

We may wish to extend the default of IPv4 to FreeBSD as a result of this.  That said, the code for setting IP_TOS still needs some examination to determine how it could do the correct thing for IPv6.

**Comment by battleblow** [comment]
Extending the OpenBSD defaults to FreeBSD does indeed result in my test case succeeding.  Will try it on the full set of failing tests tomorrow.  I'd still like to look at the option setting code a little further though.

Also, my test just added FreeBSD to the cpp conditionals, but I think that it would be better to use _BSDONLY_SOURCE.  At this point including NetBSD in the absence of evidence to the contrary is likely the right thing to do.

**Comment by battleblow** [comment]
Pushed a commit which uses _BSDONLY_SOURCE after testing it on these failing tests.  It fixes all of the initially mentioned tests, but not all of the multicast tests.  However, the remaining failures are different failures and point to a different issue.

**Comment by bsdkurt** [comment]
@battleblow IIRC on FreeBSD in the past, `sysctl -w net.inet6.ip6.v6only=0` was needed to pass the jck testing due to the way that the JDK utilizes IPv4-mapped IPv6 addresses to simultaneously support ipv6 and ipv4 on the same socket.

You may run into some issues with making this the default on FreeBSD. I suspect that the change to:

src/java.base/unix/native/libnet/PlainSocketImpl.c 

may make a system that is configured with ipv6 and the jvm `java.net.preferIPv4Stack=false` be unable to communicate with ipv4 addresses. On OpenSD, there's no way to make this work, but on Free/Net you can enable IPv4-mapped IPv6 addresses with the sysctl. Perhaps if this is an issue, you could continue to allow Free/Net to disable IPV6_V6ONLY but suppress the error if it fails. I believe this would allow for all possible modes to work on Free/Net. e.g. a java application that relies on a single socket supporting ipv6 and ipv4 could set `java.net.preferIPv4Stack=false` and `sysctl -w net.inet6.ip6.v6only=0` to get that behavior.

**Comment by battleblow** [comment]
Thanks Kurt.  My biggest concern with such a set up is that it requires users to be familiar with the correct sysctl settings and to use non-standard values to get things working.  My preference is definitely that things work as expected out of the box.  As you mention though, which this change it looks like IPv4 mapped IPv6 addresses won't be able to work.

This is good to keep in mind though for compliance testing.  I'll also give the change a bit more thought in terms of the possibilities for different configurations and whether there is a way all the functionality can be preserved without that tripping up a lot of users.
