### ISSUE TITLE
assert(len == sizeof(mem_val)) failed: unexpected data size on 32bits arch

### ISSUE THREAD

**Issue by MikaelUrankar** [battleblow/openjdk-jdk11u#77]
I hit this assert on armv7 with fastdebug build. I assume it's the same on i386.

```
# Internal Error (src/hotspot/os/bsd/os_bsd.cpp:319), pid=42571, tid=100522
# assert(len == sizeof(mem_val)) failed: unexpected data size

len=4, sizeof(mem_val)=8
sizeof(julong): 8
```
https://github.com/MikaelUrankar/openjdk-jdk11u/blob/bsd-port/src/hotspot/os/bsd/os_bsd.cpp#L319

**Comment by battleblow** [comment]
Thanks Mikael!  I've merged this fix
